#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto post generator for botdefi.io
Safe for GitHub Actions. Produces a markdown post under _posts.
"""

import os
import datetime
import random

SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "").strip() or os.path.basename(os.getcwd())

DOMAINS = [
    'botdefi.io', 'botgame.io', 'metaversebot.io', 'nftgameai.com',
    'hubgaming.io', 'esportsai.io', 'nftgamepro.com', 'botesports.com',
    'aiesports.io', 'pronftgame.com', 'botplay.io', 'botweb3ai.com',
    'botblockchain.io'
]

IMAGES = {
    'botdefi.io': [
        "https://images.pexels.com/photos/3945662/pexels-photo-3945662.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop",
        "https://source.unsplash.com/1200x630/?defi,crypto",
        "https://picsum.photos/1200/630?random=241233"
    ],
    'default': [
        "https://source.unsplash.com/1200x630/?finance,crypto",
        "https://picsum.photos/1200/630?random=9988"
    ]
}

TOPICS = [
    "Automated Market Making: Practical Tips for Bot Builders",
    "Risk Management for DeFi Bots in 2025",
    "How to Reduce Gas Cost for High-Frequency Strategies",
    "Front-running & MEV: Defensive Bot Designs",
    "Bootstrapping Liquidity: Strategies for Small Pools"
]


def pick_image(domain):
    pool = IMAGES.get(domain, IMAGES['default'])
    return random.choice(pool)


def pick_backlinks(domain):
    others = [d for d in DOMAINS if d != domain]
    random.shuffle(others)
    picked = others[:6]  # show several but limited
    # format as list markdown
    return "\n".join([f"- [{d}](https://{d})" for d in picked])


def generate_md(domain):
    today = datetime.date.today().isoformat()
    title = random.choice(TOPICS)
    image = pick_image(domain)
    desc = f"{title} — daily DeFi bot insight from {domain}"
    backlinks_md = pick_backlinks(domain)

    template = """---
layout: post
title: "__TITLE__"
date: __DATE__
author: "BotDeFi Team"
description: "__DESC__"
image: "__IMAGE__"
---

_This short insight was auto-generated by BotDeFi AI._

![__TITLE__](__IMAGE__)

<!-- ad will be inserted here -->
{% include ad.html %}

**TL;DR:** Quick practical tips for bot designers and DeFi operators.

__BODY__

---

## Key Insights
- Implement rate-limiting on order loops.
- Use statistical filters to avoid noise trades.
- Consider batched transactions to lower gas.

## Friendly Network
__BACKLINKS__

{% include analytics.html %}
"""

    # build body: simple paragraph + a small unique paragraph to avoid exact duplicates
    body_lines = []
    body_lines.append("DeFi bots need stable telemetry: track slippage, failed txs, and effective fees.")
    body_lines.append("Short time windows + poor sampling cause false signals—smooth your metrics.")
    body_text = "\n\n".join(body_lines)

    md = template.replace("__TITLE__", title)\
                 .replace("__DATE__", today)\
                 .replace("__DESC__", desc)\
                 .replace("__IMAGE__", image)\
                 .replace("__BACKLINKS__", backlinks_md)\
                 .replace("__BODY__", body_text)

    # slugify title
    slug = title.lower().replace(" ", "-").replace("/", "-")
    # sanitize to simple ascii-ish
    slug = "".join([c for c in slug if c.isalnum() or c in "-"]).strip("-")
    path = f"_posts/{today}-{slug}.md"
    return path, md


def main():
    os.makedirs("_posts", exist_ok=True)
    fn, content = generate_md(SITE_DOMAIN)
    with open(fn, "w", encoding="utf-8") as f:
        f.write(content)
    print("WROTE:", fn)


if __name__ == "__main__":
    main()
